# Generated by Django 4.0.2 on 2022-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
    ]
